package es.eventup.app.models.entity;
// Generated 25-abr-2020 19:58:36 by Hibernate Tools 4.3.1



import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Entrada generated by hbm2java
 */
@Entity
@Table(name = "entradas")
public class Entrada  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="id")
     private Long id;

    @OneToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "id_transporte", referencedColumnName = "id")
     private Transporte transporte;
    
     @NotNull
     @ManyToOne(optional = false, cascade = CascadeType.PERSIST, fetch = FetchType.LAZY)
     private User usuario;
     
     @NotNull
     @OneToOne(cascade = CascadeType.PERSIST)
     @JoinColumn(name = "id_venta", referencedColumnName = "id")
     private Venta venta;
     
     @OneToOne(cascade = CascadeType.PERSIST)
     @JoinColumn(name = "id_asistencia", referencedColumnName = "id")
     private Asistencia asistencia;
     
     @Column(name="num_asiento")
     private String numAsiento;
     
     @NotNull
     private String tipo;
     

    public Entrada() {
    }
	
	public Entrada(@NotNull User usuario, @NotNull Venta venta) {
		super();
		this.usuario = usuario;
		this.venta = venta;
	}

	public Entrada(Transporte transporte, @NotNull User usuario, @NotNull Venta venta, String numAsiento,
			@NotNull String tipo) {
		super();
		this.transporte = transporte;
		this.usuario = usuario;
		this.venta = venta;
		this.numAsiento = numAsiento;
		this.tipo = tipo;
	}

	public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
  

	public Transporte getTransporte() {
		return transporte;
	}


	public void setTransporte(Transporte transporte) {
		this.transporte = transporte;
	}


	public User getUsuario() {
		return usuario;
	}


	public void setUsuario(User usuario) {
		this.usuario = usuario;
	}


	public Venta getVenta() {
		return venta;
	}


	public void setVenta(Venta venta) {
		this.venta = venta;
	}


	public String getNumAsiento() {
        return this.numAsiento;
    }
    
    public void setNumAsiento(String numAsiento) {
        this.numAsiento = numAsiento;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

	public Asistencia getAsistencia() {
		return asistencia;
	}

	public void setAsistencia(Asistencia asistencia) {
		this.asistencia = asistencia;
	}
    
    

}


