version: '3.4'

services:
  mysql:
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_DATABASE: "eventup"
      MYSQL_USER: "eventup"
      MYSQL_PASSWORD: "3v3ntUP"
      MYSQL_ROOT_PASSWORD: "example"
    ports:
      - 3306:3306
    networks:
      monitoring:
        aliases:
          - mysql
    expose:
      - 3306
    volumes:
      - ./mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      monitoring:
        aliases:
          - adminer


# ---- MICROSERVICIOS ----

  eventup-service:
    image: adlian25/eventup:0.0.1-SNAPSHOT
    restart: always
    depends_on:
     - mysql
    ports:
      - 80:80
    networks:
      monitoring:
        aliases:
          - eventup-service
    environment:
      # MONGODB
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/eventup?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
      # LOGGING
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=OFF
      - LOGGING_LEVEL_ROOT=OFF
networks:
  monitoring:
